export const SOCKET_EVENTS = {
  ORDER_NEW: "order:new",
  ORDER_CONFIRMED: "order:confirmed",
  ORDER_CANCELLED: "order:cancelled",
  USER_NEW: "user:new",
  BOOKING_TABLE_NEW: "booking:table:new",
  BOOKING_TABLE_UPDATED: "booking:table:updated",
  BOOKING_TABLE_CANCELLED: "booking:table:cancelled",
  BOOKING_EVENT_NEW: "booking:event:new",
  BOOKING_EVENT_UPDATED: "booking:event:updated",
  BOOKING_EVENT_CANCELLED: "booking:event:cancelled",
  REVIEW_NEW: "review:new",
  ADMIN_CREATED: "admin:created",
  ADMIN_DELETED: "admin:deleted",
  FOOD_CREATED: "food:created",
  FOOD_UPDATED: "food:updated",
  FOOD_DELETED: "food:deleted",
  CATEGORY_CREATED: "category:created",
  CATEGORY_UPDATED: "category:updated",
  CATEGORY_DELETED: "category:deleted",
  VISITOR_NEW: "visitor:new",
  VISITOR_CONSENT_PENDING: "visitor:consent:pending",
  VISITOR_CONSENT_ACCEPTED: "visitor:consent:accepted",
  VISITOR_CONSENT_DECLINED: "visitor:consent:declined",
};
